<?php
/**
 * map domain name tlds to default country.
 */
return array(
    'ad' => array('countryCode' => 'ad', 'displayText' => 'Andorra' ),
    'ae' => array('countryCode' => 'ae', 'displayText' => 'United Arab Emirates' ),
    'af' => array('countryCode' => 'af', 'displayText' => 'Afghanistan' ),
    'ag' => array('countryCode' => 'ag', 'displayText' => 'Antigua and Barbuda' ),
    'ai' => array('countryCode' => 'ai', 'displayText' => 'Anguilla' ),
    'al' => array('countryCode' => 'al', 'displayText' => 'Albania' ),
    'am' => array('countryCode' => 'am', 'displayText' => 'Armenia' ),
    'an' => array('countryCode' => 'an', 'displayText' => 'Netherlands Antilles' ),
    'ao' => array('countryCode' => 'ao', 'displayText' => 'Angola' ),
    'aq' => array('countryCode' => 'aq', 'displayText' => 'Antarctica' ),
    'ar' => array('countryCode' => 'ar', 'displayText' => 'Argentina' ),
    'as' => array('countryCode' => 'as', 'displayText' => 'American Samoa' ),
    'at' => array('countryCode' => 'at', 'displayText' => 'Austria' ),
    'au' => array('countryCode' => 'au', 'displayText' => 'Australia' ),
    'aw' => array('countryCode' => 'aw', 'displayText' => 'Aruba' ),
    'az' => array('countryCode' => 'az', 'displayText' => 'Azerbaijan' ),
    'ba' => array('countryCode' => 'ba', 'displayText' => 'Bosnia and Herzegovina' ),
    'bb' => array('countryCode' => 'bb', 'displayText' => 'Barbados' ),
    'bd' => array('countryCode' => 'bd', 'displayText' => 'Bangladesh' ),
    'be' => array('countryCode' => 'be', 'displayText' => 'Belgium' ),
    'bf' => array('countryCode' => 'bf', 'displayText' => 'Burkina Faso' ),
    'bg' => array('countryCode' => 'bg', 'displayText' => 'Bulgaria' ),
    'bh' => array('countryCode' => 'bh', 'displayText' => 'Bahrain' ),
    'bi' => array('countryCode' => 'bi', 'displayText' => 'Burundi' ),
    'bj' => array('countryCode' => 'bj', 'displayText' => 'Benin' ),
    'bm' => array('countryCode' => 'bm', 'displayText' => 'Bermuda' ),
    'bn' => array('countryCode' => 'bn', 'displayText' => 'Brunei Darussalam' ),
    'bo' => array('countryCode' => 'bo', 'displayText' => 'Bolivia' ),
    'br' => array('countryCode' => 'br', 'displayText' => 'Brazil' ),
    'bs' => array('countryCode' => 'bs', 'displayText' => 'Bahamas' ),
    'bt' => array('countryCode' => 'bt', 'displayText' => 'Bhutan' ),
    'bv' => array('countryCode' => 'bv', 'displayText' => 'Bouvet Island' ),
    'bw' => array('countryCode' => 'bw', 'displayText' => 'Botswana' ),
    'by' => array('countryCode' => 'by', 'displayText' => 'Belarus' ),
    'bz' => array('countryCode' => 'bz', 'displayText' => 'Belize' ),
    'ca' => array('countryCode' => 'ca', 'displayText' => 'Canada' ),
    'cc' => array('countryCode' => 'cc', 'displayText' => 'Cocos (Keeling) Islands' ),
    'cf' => array('countryCode' => 'cf', 'displayText' => 'Central African Republic' ),
    'cg' => array('countryCode' => 'cg', 'displayText' => 'Congo' ),
    'ch' => array('countryCode' => 'ch', 'displayText' => 'Switzerland' ),
    'ci' => array('countryCode' => 'ci', 'displayText' => "Cote D'Ivoire (Ivory Coast)" ),
    'ck' => array('countryCode' => 'ck', 'displayText' => 'Cook Islands' ),
    'cl' => array('countryCode' => 'cl', 'displayText' => 'Chile' ),
    'cm' => array('countryCode' => 'cm', 'displayText' => 'Cameroon' ),
    'cn' => array('countryCode' => 'cn', 'displayText' => 'China' ),
    'co' => array('countryCode' => 'co', 'displayText' => 'Colombia' ),
    'cr' => array('countryCode' => 'cr', 'displayText' => 'Costa Rica' ),
    'cu' => array('countryCode' => 'cu', 'displayText' => 'Cuba' ),
    'cv' => array('countryCode' => 'cv', 'displayText' => 'Cape Verde' ),
    'cx' => array('countryCode' => 'cx', 'displayText' => 'Christmas Island' ),
    'cy' => array('countryCode' => 'cy', 'displayText' => 'Cyprus' ),
    'cz' => array('countryCode' => 'cz', 'displayText' => 'Czech Republic' ),
    'de' => array('countryCode' => 'de', 'displayText' => 'Germany' ),
    'dj' => array('countryCode' => 'dj', 'displayText' => 'Djibouti' ),
    'dk' => array('countryCode' => 'dk', 'displayText' => 'Denmark' ),
    'dm' => array('countryCode' => 'dm', 'displayText' => 'Dominica' ),
    'do' => array('countryCode' => 'do', 'displayText' => 'Dominican Republic' ),
    'dz' => array('countryCode' => 'dz', 'displayText' => 'Algeria' ),
    'ec' => array('countryCode' => 'ec', 'displayText' => 'Ecuador' ),
    'ee' => array('countryCode' => 'ee', 'displayText' => 'Estonia' ),
    'eg' => array('countryCode' => 'eg', 'displayText' => 'Egypt' ),
    'eh' => array('countryCode' => 'eh', 'displayText' => 'Western Sahara' ),
    'er' => array('countryCode' => 'er', 'displayText' => 'Eritrea' ),
    'es' => array('countryCode' => 'es', 'displayText' => 'Spain' ),
    'et' => array('countryCode' => 'et', 'displayText' => 'Ethiopia' ),
    'fi' => array('countryCode' => 'fi', 'displayText' => 'Finland' ),
    'fj' => array('countryCode' => 'fj', 'displayText' => 'Fiji' ),
    'fk' => array('countryCode' => 'fk', 'displayText' => 'Falkland Islands (Malvinas)' ),
    'fm' => array('countryCode' => 'fm', 'displayText' => 'Micronesia' ),
    'fo' => array('countryCode' => 'fo', 'displayText' => 'Faroe Islands' ),
    'fr' => array('countryCode' => 'fr', 'displayText' => 'France' ),
    'fx' => array('countryCode' => 'fx', 'displayText' => 'France, Metropolitan' ),
    'ga' => array('countryCode' => 'ga', 'displayText' => 'Gabon' ),
    'gd' => array('countryCode' => 'gd', 'displayText' => 'Grenada' ),
    'ge' => array('countryCode' => 'ge', 'displayText' => 'Georgia' ),
    'gf' => array('countryCode' => 'gf', 'displayText' => 'French Guiana' ),
    'gh' => array('countryCode' => 'gh', 'displayText' => 'Ghana' ),
    'gi' => array('countryCode' => 'gi', 'displayText' => 'Gibraltar' ),
    'gl' => array('countryCode' => 'gl', 'displayText' => 'Greenland' ),
    'gm' => array('countryCode' => 'gm', 'displayText' => 'Gambia' ),
    'gn' => array('countryCode' => 'gn', 'displayText' => 'Guinea' ),
    'gp' => array('countryCode' => 'gp', 'displayText' => 'Guadeloupe' ),
    'gq' => array('countryCode' => 'gq', 'displayText' => 'Equatorial Guinea' ),
    'gr' => array('countryCode' => 'gr', 'displayText' => 'Greece' ),
    'gs' => array('countryCode' => 'gs', 'displayText' => 'S. Georgia and S. Sandwich Isls.' ),
    'gt' => array('countryCode' => 'gt', 'displayText' => 'Guatemala' ),
    'gu' => array('countryCode' => 'gu', 'displayText' => 'Guam' ),
    'gw' => array('countryCode' => 'gw', 'displayText' => 'Guinea-Bissau' ),
    'gy' => array('countryCode' => 'gy', 'displayText' => 'Guyana' ),
    'hk' => array('countryCode' => 'hk', 'displayText' => 'Hong Kong' ),
    'hm' => array('countryCode' => 'hm', 'displayText' => 'Heard and McDonald Islands' ),
    'hn' => array('countryCode' => 'hn', 'displayText' => 'Honduras' ),
    'hr' => array('countryCode' => 'hr', 'displayText' => 'Croatia (Hrvatska)' ),
    'ht' => array('countryCode' => 'ht', 'displayText' => 'Haiti' ),
    'hu' => array('countryCode' => 'hu', 'displayText' => 'Hungary' ),
    'id' => array('countryCode' => 'id', 'displayText' => 'Indonesia' ),
    'ie' => array('countryCode' => 'ie', 'displayText' => 'Ireland' ),
    'il' => array('countryCode' => 'il', 'displayText' => 'Israel' ),
    'in' => array('countryCode' => 'in', 'displayText' => 'India' ),
    'io' => array('countryCode' => 'io', 'displayText' => 'British Indian Ocean Territory' ),
    'iq' => array('countryCode' => 'iq', 'displayText' => 'Iraq' ),
    'ir' => array('countryCode' => 'ir', 'displayText' => 'Iran' ),
    'is' => array('countryCode' => 'is', 'displayText' => 'Iceland' ),
    'it' => array('countryCode' => 'it', 'displayText' => 'Italy' ),
    'jm' => array('countryCode' => 'jm', 'displayText' => 'Jamaica' ),
    'jo' => array('countryCode' => 'jo', 'displayText' => 'Jordan' ),
    'jp' => array('countryCode' => 'jp', 'displayText' => 'Japan' ),
    'ke' => array('countryCode' => 'ke', 'displayText' => 'Kenya' ),
    'kg' => array('countryCode' => 'kg', 'displayText' => 'Kyrgyzstan' ),
    'kh' => array('countryCode' => 'kh', 'displayText' => 'Cambodia' ),
    'ki' => array('countryCode' => 'ki', 'displayText' => 'Kiribati' ),
    'km' => array('countryCode' => 'km', 'displayText' => 'Comoros' ),
    'kn' => array('countryCode' => 'kn', 'displayText' => 'Saint Kitts and Nevis' ),
    'kp' => array('countryCode' => 'kp', 'displayText' => 'Korea (North)' ),
    'kr' => array('countryCode' => 'kr', 'displayText' => 'Korea (South)' ),
    'kw' => array('countryCode' => 'kw', 'displayText' => 'Kuwait' ),
    'ky' => array('countryCode' => 'ky', 'displayText' => 'Cayman Islands' ),
    'kz' => array('countryCode' => 'kz', 'displayText' => 'Kazakhstan' ),
    'la' => array('countryCode' => 'la', 'displayText' => 'Laos' ),
    'lb' => array('countryCode' => 'lb', 'displayText' => 'Lebanon' ),
    'lc' => array('countryCode' => 'lc', 'displayText' => 'Saint Lucia' ),
    'li' => array('countryCode' => 'li', 'displayText' => 'Liechtenstein' ),
    'lk' => array('countryCode' => 'lk', 'displayText' => 'Sri Lanka' ),
    'lr' => array('countryCode' => 'lr', 'displayText' => 'Liberia' ),
    'ls' => array('countryCode' => 'ls', 'displayText' => 'Lesotho' ),
    'lt' => array('countryCode' => 'lt', 'displayText' => 'Lithuania' ),
    'lu' => array('countryCode' => 'lu', 'displayText' => 'Luxembourg' ),
    'lv' => array('countryCode' => 'lv', 'displayText' => 'Latvia' ),
    'ly' => array('countryCode' => 'ly', 'displayText' => 'Libya' ),
    'ma' => array('countryCode' => 'ma', 'displayText' => 'Morocco' ),
    'mc' => array('countryCode' => 'mc', 'displayText' => 'Monaco' ),
    'md' => array('countryCode' => 'md', 'displayText' => 'Moldova' ),
    'mg' => array('countryCode' => 'mg', 'displayText' => 'Madagascar' ),
    'mh' => array('countryCode' => 'mh', 'displayText' => 'Marshall Islands' ),
    'mk' => array('countryCode' => 'mk', 'displayText' => 'Macedonia' ),
    'ml' => array('countryCode' => 'ml', 'displayText' => 'Mali' ),
    'mm' => array('countryCode' => 'mm', 'displayText' => 'Myanmar' ),
    'mn' => array('countryCode' => 'mn', 'displayText' => 'Mongolia' ),
    'mo' => array('countryCode' => 'mo', 'displayText' => 'Macau' ),
    'mp' => array('countryCode' => 'mp', 'displayText' => 'Northern Mariana Islands' ),
    'mq' => array('countryCode' => 'mq', 'displayText' => 'Martinique' ),
    'mr' => array('countryCode' => 'mr', 'displayText' => 'Mauritania' ),
    'ms' => array('countryCode' => 'ms', 'displayText' => 'Montserrat' ),
    'mt' => array('countryCode' => 'mt', 'displayText' => 'Malta' ),
    'mu' => array('countryCode' => 'mu', 'displayText' => 'Mauritius' ),
    'mv' => array('countryCode' => 'mv', 'displayText' => 'Maldives' ),
    'mw' => array('countryCode' => 'mw', 'displayText' => 'Malawi' ),
    'mx' => array('countryCode' => 'mx', 'displayText' => 'Mexico' ),
    'my' => array('countryCode' => 'my', 'displayText' => 'Malaysia' ),
    'mz' => array('countryCode' => 'mz', 'displayText' => 'Mozambique' ),
    'na' => array('countryCode' => 'na', 'displayText' => 'Namibia' ),
    'nc' => array('countryCode' => 'nc', 'displayText' => 'New Caledonia' ),
    'ne' => array('countryCode' => 'ne', 'displayText' => 'Niger' ),
    'nf' => array('countryCode' => 'nf', 'displayText' => 'Norfolk Island' ),
    'ng' => array('countryCode' => 'ng', 'displayText' => 'Nigeria' ),
    'ni' => array('countryCode' => 'ni', 'displayText' => 'Nicaragua' ),
    'nl' => array('countryCode' => 'nl', 'displayText' => 'Netherlands' ),
    'no' => array('countryCode' => 'no', 'displayText' => 'Norway' ),
    'np' => array('countryCode' => 'np', 'displayText' => 'Nepal' ),
    'nr' => array('countryCode' => 'nr', 'displayText' => 'Nauru' ),
    'nt' => array('countryCode' => 'nt', 'displayText' => 'Neutral Zone' ),
    'nu' => array('countryCode' => 'nu', 'displayText' => 'Niue' ),
    'nz' => array('countryCode' => 'nz', 'displayText' => 'New Zealand (Aotearoa)' ),
    'om' => array('countryCode' => 'om', 'displayText' => 'Oman' ),
    'pa' => array('countryCode' => 'pa', 'displayText' => 'Panama' ),
    'pe' => array('countryCode' => 'pe', 'displayText' => 'Peru' ),
    'pf' => array('countryCode' => 'pf', 'displayText' => 'French Polynesia' ),
    'pg' => array('countryCode' => 'pg', 'displayText' => 'Papua New Guinea' ),
    'ph' => array('countryCode' => 'ph', 'displayText' => 'Philippines' ),
    'pk' => array('countryCode' => 'pk', 'displayText' => 'Pakistan' ),
    'pl' => array('countryCode' => 'pl', 'displayText' => 'Poland' ),
    'pm' => array('countryCode' => 'pm', 'displayText' => 'St. Pierre and Miquelon' ),
    'pn' => array('countryCode' => 'pn', 'displayText' => 'Pitcairn' ),
    'pr' => array('countryCode' => 'pr', 'displayText' => 'Puerto Rico' ),
    'pt' => array('countryCode' => 'pt', 'displayText' => 'Portugal' ),
    'pw' => array('countryCode' => 'pw', 'displayText' => 'Palau' ),
    'py' => array('countryCode' => 'py', 'displayText' => 'Paraguay' ),
    'qa' => array('countryCode' => 'qa', 'displayText' => 'Qatar' ),
    're' => array('countryCode' => 're', 'displayText' => 'Reunion' ),
    'ro' => array('countryCode' => 'ro', 'displayText' => 'Romania' ),
    'ru' => array('countryCode' => 'ru', 'displayText' => 'Russia' ),
    'rw' => array('countryCode' => 'rw', 'displayText' => 'Rwanda' ),
    'sa' => array('countryCode' => 'sa', 'displayText' => 'Saudi Arabia' ),
    'sb' => array('countryCode' => 'sb', 'displayText' => 'Solomon Islands' ),
    'sc' => array('countryCode' => 'sc', 'displayText' => 'Seychelles' ),
    'sd' => array('countryCode' => 'sd', 'displayText' => 'Sudan' ),
    'se' => array('countryCode' => 'se', 'displayText' => 'Sweden' ),
    'sg' => array('countryCode' => 'sg', 'displayText' => 'Singapore' ),
    'sh' => array('countryCode' => 'sh', 'displayText' => 'St. Helena' ),
    'si' => array('countryCode' => 'si', 'displayText' => 'Slovenia' ),
    'sj' => array('countryCode' => 'sj', 'displayText' => 'Svalbard and Jan Mayen Islands' ),
    'sk' => array('countryCode' => 'sk', 'displayText' => 'Slovak Republic' ),
    'sl' => array('countryCode' => 'sl', 'displayText' => 'Sierra Leone' ),
    'sm' => array('countryCode' => 'sm', 'displayText' => 'San Marino' ),
    'sn' => array('countryCode' => 'sn', 'displayText' => 'Senegal' ),
    'so' => array('countryCode' => 'so', 'displayText' => 'Somalia' ),
    'sr' => array('countryCode' => 'sr', 'displayText' => 'Suriname' ),
    'st' => array('countryCode' => 'st', 'displayText' => 'Sao Tome and Principe' ),
    'sv' => array('countryCode' => 'sv', 'displayText' => 'El Salvador' ),
    'sy' => array('countryCode' => 'sy', 'displayText' => 'Syria' ),
    'sz' => array('countryCode' => 'sz', 'displayText' => 'Swaziland' ),
    'tc' => array('countryCode' => 'tc', 'displayText' => 'Turks and Caicos Islands' ),
    'td' => array('countryCode' => 'td', 'displayText' => 'Chad' ),
    'tf' => array('countryCode' => 'tf', 'displayText' => 'French Southern Territories' ),
    'tg' => array('countryCode' => 'tg', 'displayText' => 'Togo' ),
    'th' => array('countryCode' => 'th', 'displayText' => 'Thailand' ),
    'tj' => array('countryCode' => 'tj', 'displayText' => 'Tajikistan' ),
    'tk' => array('countryCode' => 'tk', 'displayText' => 'Tokelau' ),
    'tm' => array('countryCode' => 'tm', 'displayText' => 'Turkmenistan' ),
    'tn' => array('countryCode' => 'tn', 'displayText' => 'Tunisia' ),
    'to' => array('countryCode' => 'to', 'displayText' => 'Tonga' ),
    'tp' => array('countryCode' => 'tp', 'displayText' => 'East Timor' ),
    'tr' => array('countryCode' => 'tr', 'displayText' => 'Turkey' ),
    'tt' => array('countryCode' => 'tt', 'displayText' => 'Trinidad and Tobago' ),
    'tv' => array('countryCode' => 'tv', 'displayText' => 'Tuvalu' ),
    'tw' => array('countryCode' => 'tw', 'displayText' => 'Taiwan' ),
    'tz' => array('countryCode' => 'tz', 'displayText' => 'Tanzania' ),
    'ua' => array('countryCode' => 'ua', 'displayText' => 'Ukraine' ),
    'ug' => array('countryCode' => 'ug', 'displayText' => 'Uganda' ),
    'uk' => array('countryCode' => 'uk', 'displayText' => 'United Kingdom' ),
    'um' => array('countryCode' => 'um', 'displayText' => 'US Minor Outlying Islands' ),
    'us' => array('countryCode' => 'us', 'displayText' => 'United States' ),
    'uy' => array('countryCode' => 'uy', 'displayText' => 'Uruguay' ),
    'uz' => array('countryCode' => 'uz', 'displayText' => 'Uzbekistan' ),
    'va' => array('countryCode' => 'va', 'displayText' => 'Vatican City State (Holy See)' ),
    'vc' => array('countryCode' => 'vc', 'displayText' => 'Saint Vincent and the Grenadines' ),
    've' => array('countryCode' => 've', 'displayText' => 'Venezuela' ),
    'vg' => array('countryCode' => 'vg', 'displayText' => 'Virgin Islands (British)' ),
    'vi' => array('countryCode' => 'vi', 'displayText' => 'Virgin Islands (U.S.)' ),
    'vn' => array('countryCode' => 'vn', 'displayText' => 'Viet Nam' ),
    'vu' => array('countryCode' => 'vu', 'displayText' => 'Vanuatu' ),
    'wf' => array('countryCode' => 'wf', 'displayText' => 'Wallis and Futuna Islands' ),
    'ws' => array('countryCode' => 'ws', 'displayText' => 'Samoa' ),
    'ye' => array('countryCode' => 'ye', 'displayText' => 'Yemen' ),
    'yt' => array('countryCode' => 'yt', 'displayText' => 'Mayotte' ),
    'yu' => array('countryCode' => 'yu', 'displayText' => 'Yugoslavia' ),
    'za' => array('countryCode' => 'za', 'displayText' => 'South Africa' ),
    'zm' => array('countryCode' => 'zm', 'displayText' => 'Zambia' ),
    'zr' => array('countryCode' => 'zr', 'displayText' => 'Zaire' ),
    'zw' => array('countryCode' => 'zw', 'displayText' => 'Zimbabwe' ),
    'com' => array('countryCode' => 'us', 'displayText' => 'US Commercial', 'notCountry' =>true ),
    'edu' => array('countryCode' => 'us', 'displayText' => 'US Educational', 'notCountry' =>true ),
    'gov' => array('countryCode' => 'us', 'displayText' => 'US Government', 'notCountry' =>true ),
    'mil' => array('countryCode' => 'us', 'displayText' => 'US Military', 'notCountry' =>true ),
    'net' => array('countryCode' => 'us', 'displayText' => 'Network', 'notCountry' =>true ),
    'org' => array('countryCode' => 'us', 'displayText' => 'Non-Profit Organization', 'notCountry' =>true ),
);
