<?php
///////////////////////////////SETTINGS\\\\\\\\\\\\\\\\\\\\\\\\\\\\
function theme_init() {
	//THEME SETTINGS
	register_setting("flatty_theme", "flatty_light_style");
	register_setting("flatty_theme", "flatty_hide_sidebar_separator");
	register_setting("flatty_theme", "flatty_post_style");
	register_setting("flatty_theme", "flatty_sidebar_minimal");

	//WHITELABELING
	register_setting("flatty_theme", "flatty_wp_hide_topbar");
	register_setting("flatty_theme", "flatty_wp_hide_topbar_logo");
	register_setting("flatty_theme", "flatty_wp_hide_footer");
	register_setting("flatty_theme", "flatty_wordpress_remove_generator");
}

add_action("admin_init","theme_init");

//////////////////////////////////////////////////////////////////////////////////////////////////PAGE
function options_main_theme() {
	?>

	<form method='post' action='options.php'>

		<div class="wrap flatty-form">

	        <div class="page-title">
	            <img src="<?php echo plugins_url(FLATTY_PLUGIN_URL . 'assets/flatty-logo.png') ?>" class="flatty-logo"/>
	            <div class="header">Theme</div>
	        </div>

				<div id="theme-box" class="postbox flatty">
					<div class="title">
	                    <i class="fa fa-object-ungroup" style="background-color: #4ac9c9;"></i>
	                    <span>Theme</span>
	                </div>

					<div class="option">
						<label for="flatty_light_style">Choose the light side</label>
						<input
							type="checkbox"
							name="flatty_light_style"
							id="flatty_light_style"
							value='1'
							<?php checked(1, get_option('flatty_light_style')); ?>
						/>
					</div>

					<div class="option">
						<label for="flatty_post_style">Disable Flatty's "new post" styling</label>
						<input
							type="checkbox"
							name="flatty_post_style"
							id="flatty_post_style"
							value='1'
							<?php checked(1, get_option('flatty_post_style')); ?>
						/>
					</div>

	            </div>

				<div id="sidebar-box" class="postbox flatty">
					<div class="title">
	                    <i class="fa fa-tasks" style="background-color: #6b90a7;"></i>
	                    <span>Sidebar</span>
	                </div>

					<div class="option">
						<label for="flatty_sidebar_minimal">Enable Flatty's "minimal sidebar" styling</label>
						<input
							type="checkbox"
							name="flatty_sidebar_minimal"
							id="flatty_sidebar_minimal"
							value='1'
							<?php checked(1, get_option('flatty_sidebar_minimal')); ?>
						/>
					</div>

					<div class="option">
						<label for="flatty_hide_sidebar_separator">Hide sidebar white separator</label>
						<input
							type="checkbox"
							name="flatty_hide_sidebar_separator"
							id="flatty_hide_sidebar_separator"
							value='1'
							<?php checked(1, get_option('flatty_hide_sidebar_separator')); ?>
						/>
					</div>

	            </div>

				<div id="whitelabel-box" class="postbox flatty">
					<div class="title">
	                    <i class="fa fa-wordpress" style="background-color: #404386;"></i>
	                    <span>Whitelabel Wordpress</span>
	                </div>

					<div class="option">
						<label for="flatty_wordpress_remove_generator">Remove Wordpress Meta tags</label>
						<div class="flatty-description">Like 'generated by Wordpress' and Wordpress version</div>
						<input
							type="checkbox"
							name="flatty_wordpress_remove_generator"
							id="flatty_wordpress_remove_generator"
							value='1'
							<?php checked(1, get_option('flatty_wordpress_remove_generator')); ?>
						/>
					</div>

					<div class="option">
						<label for="flatty_wp_hide_footer">Hide Wordpress Top Bar</label>
						<input
							type="checkbox"
							name="flatty_wp_hide_topbar"
							id="flatty_wp_hide_topbar"
							value='1'
							<?php checked(1, get_option('flatty_wp_hide_topbar')); ?>
						/>
					</div>

					<div class="option">
						<label for="flatty_wp_hide_footer">Hide Wordpress Logo</label>
						<input
							type="checkbox"
							name="flatty_wp_hide_topbar_logo"
							id="flatty_wp_hide_topbar_logo"
							value='1'
							<?php checked(1, get_option('flatty_wp_hide_topbar_logo')); ?>
						/>
					</div>

					<div class="option">
						<label for="flatty_wp_hide_footer">Hide Wordpress footer</label>
						<input
							type="checkbox"
							name="flatty_wp_hide_footer"
							id="flatty_wp_hide_footer"
							value='1'
							<?php checked(1, get_option('flatty_wp_hide_footer')); ?>
						/>
					</div>

	            </div>

		</div>

		<div class="buttons-container">
			<?php
				settings_fields('flatty_theme');
				submit_button('', 'primary large flatty-button-update');
			?>
			<div class="flatty-single">*Don't forget to save changes</div>
		</div>

	</form>

	<?php
}

?>
